Clean up CSS and HTML formatting
epic-power-rpg/roll20 pull request #10
Opened 2022-10-23 19:36 UTC by jazeee

Replace tabs with 2 spaces, and then do an initial pass of formatting
in the HTML.
(We'd probably benefit from moving the code out of HTML
and into a lintable file.)

Add README to help with formatting

2022-10-23 19:36 UTC, jazeee commented on ui/roll20_character_sheet_0.2.css
> +
In VSCode, I ran the auto-formatter, which made these files more consistent.
Consider reviewing ignoring whitespace:
https://github.com/epic-power-rpg/roll20/pull/10/files?diff=unified&w=1

2022-10-23 19:38 UTC, jazeee commented
Note - if you are in the midst of making code changes, I can always delete this PR and re-do the auto-formatting.

2022-10-24 02:32 UTC, johnlamping commented on ui/roll20_character_sheet_0.2.css
> +  /* Make the height work for span. */
This comment applies to the line before, so it should move up a line.

2022-10-24 02:33 UTC, johnlamping commented on ui/roll20_character_sheet_0.2.css
> +  /* Get rid of the space the sheet puts above us. */
Same here: Needs to move up a line.

2022-10-24 02:35 UTC, johnlamping commented on ui/roll20_character_sheet_0.2.css
> +  /* and make rows overlap */
Same here: Needs to move up a line.

2022-10-24 02:35 UTC, johnlamping commented on ui/roll20_character_sheet_0.2.css
> +  /* and make rows overlap */
Same here: Needs to move up a line.

2022-10-24 02:36 UTC, johnlamping commented on ui/roll20_character_sheet_0.2.css
> +  /* and make rows overlap */
Same here: Needs to move up a line.

2022-10-24 02:36 UTC, johnlamping commented on ui/roll20_character_sheet_0.2.css
> +  /* Make consecutive buttons overlap */
Same here: Needs to move up a line.

2022-10-24 02:36 UTC, johnlamping commented on ui/roll20_character_sheet_0.2.css
> +  /* and make rows overlap */
Same here: Needs to move up a line.

2022-10-24 02:38 UTC, johnlamping requested changes
There were a few places where the linter moved a comment after the line it applies do. Other than that, looks good.

P.S. This code is extremely ugly, which has made it hard to debug, and has led to it becoming even uglier as I added to it. I don't have a good sense of how to write good css, but this is certainly not it. If you have any suggestions on how to improve it, I'd love to hear them.

2022-10-24 16:30 UTC, jazeee commented
> There were a few places where the linter moved a comment after the line it applies do. Other than that, looks good.
> 
> P.S. This code is extremely ugly, which has made it hard to debug, and has led to it becoming even uglier as I added to it. I don't have a good sense of how to write good css, but this is certainly not it. If you have any suggestions on how to improve it, I'd love to hear them.

I'll be digging further into how to clean things up. Auto-formatting gets us started, but I'm going to need to dig in further on it.

2022-10-24 16:44 UTC, johnlamping approved these changes
Thanks!

2022-10-24 16:52 UTC, merged